version: '2'
services:
  application:
    image: euclid1990/ubuntu-server
    hostname: blog
    volumes:
      - ./blog:/var/www/html/blog
      - ./adminer:/var/www/html/adminer
  mariadb:
    image: mariadb
    ports:
      - "5000:3306"
    hostname: mysql  
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blog
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./var/log/mysql:/var/log/mysql
  php:
    image: euclid1990/php5.6-fpm
    ports:
      - "5010:9000"
    volumes_from:
      - application
    links:
      - mariadb:mysql
  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "5020:80"
    links:
      - php
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx_conf:/etc/nginx/conf.d
  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - mariadb:mysql
    ports:
      - 5030:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root123             