version: '2'
services:
  application:
    image: euclid1990/ubuntu-server
    hostname: blog_server
    volumes:
      - ./public/blog:/var/www/html/blog
      - ./public/adminer:/var/www/html/adminer
  mariadb:
    image: mariadb
    hostname: blog_mysql  
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blog
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
  php:
    image: euclid1990/php5.6-fpm
    hostname: blog_php
    ports:
      - "5010:9000"
    volumes_from:
      - application
    links:
      - mariadb:mysql
  nginx:
    image: nginx
    hostname: blog_nginx
    ports:
      - "5020:80"
    links:
      - php
    volumes_from:
      - application
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: blog_phpmyadmin
    links:
      - mariadb:mysql
    ports:
      - 5030:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root123             